### ISSUE TITLE
Feet fixed to a different position

### ISSUE THREAD

**Issue by andreadelprete** [robotology/icub-gazebo#13]
I'm using the model iCub_feet_fixed to avoid the annoying sliding of the robot's feet on the ground. However I'd like to have iCub's feet in a different position from where they are in the initial configuration.
Is anyone aware of a way to do that?
I think the only way would be to spawn the robot in the simulator in a configuration that is different from "all the joints at 0 degrees".

**Comment by traversaro** [comment]
I think we fixed long ago the drifting of the foot, so I think we can close this issue.
