### ISSUE TITLE
icub_with_hands does not work on Gazebo

### ISSUE THREAD

**Issue by robertocalandra** [robotology/icub-gazebo#14]
As title, the icub_with_hands doesn't seems to work on Gazebo. When trying to insert it, no icub is created and nothing seems to happens.

**Comment by frank-foerster** [comment]
I tried to use this 'model' in the last two days and the iCub is inserted now. But the hands don't seem to be 'controllable', that is, the visual controls for all hand joints (except for the wrist), are not being shown in the yarpmotorgui. Has there been any update on this since this issue was discussed last?

**Comment by traversaro** [comment]
Last week I believe that @Yeshasvitvs had the same problem, and he was able to solve it with the help of @randaz81 . Let's see if they can help you.

**Comment by Yeshasvitvs** [comment]
change the "parts" in yarpmotorgui.ini file of the icub_with_hands with 
parts (head  torso left_arm right_arm left_hand right_hand right_leg left_leg)

**Comment by traversaro** [comment]
I see, probably some work need to be done to refactor the wrappers to be sure to expose the same  (yarp) interface on icub_gazebo and on the real robot.

**Comment by frank-foerster** [comment]
Thanks, that did the trick. Now I just have to figure out how not to have the iCub fall immediately upon adding it to the world and break its fingers right away ;)

**Comment by Yeshasvitvs** [comment]
please note that Gazebo model does not include all the DOF for the hand as in real robot @randaz81 can give you further information on this

**Comment by randaz81** [comment]
This module is currently WIP. All the DOFs are now available (from this morning).
Wrapper is going to be fixed later this week.

**Comment by randaz81** [comment]
I pushed a new version of the **icub_with_hands** model with the wrapper fixed to control the whole arm (15 joints). The part names are the same used on the real robot (**left_arm**, **right_arm**)
I also revised the **icub** model which now opens, instead, two different parts (**left_arm_no_hand**, **right_arm_no_hand**). This to remark the fact the those parts (which control only a limited number of joints) are different from the real robot.

**Comment by traversaro** [comment]
@randaz81 can I revert the change of the names of the port in the icub without hands to left_arm / right_arm ?

 I agree that we should distinguish them, but this change broke all our controllers and tutorials two days before the `CoDyCo` project review meeting. : )

**Comment by randaz81** [comment]
yes, of course. Let's review all the models one by one after demo.

**Comment by traversaro** [comment]
:+1:

**Comment by traversaro** [comment]
We have now a working model with hands, thanks to @randaz81 .
