### ISSUE TITLE
[iCub] wrong leg limits

### ISSUE THREAD

**Issue by francesco-romano** [robotology/icub-gazebo#19]
It seems that the min and max limits are exchanged (at least for the legs)

**Comment by traversaro** [comment]
For models generated with the "old" generation procedure, limits are copied from the urdf files provided by UPMC :  https://github.com/robotology-playground/icub-model-generator/blob/master/src/icub_urdf_sdf_generator.cpp#L679

We should then modify the source files : 
 * https://github.com/robotology-playground/icub-model-generator/blob/master/data/urdf_paris/icub_simple/icub_simple.xml
 * https://github.com/robotology-playground/icub-model-generator/blob/master/data/urdf_paris/icub/icub.xml 
or get the limits from some other source, and then regenerate all the files.

**Comment by traversaro** [comment]
Limits issue originally tracked in https://github.com/robotology/codyco-superbuild/issues/55 .

**Comment by traversaro** [comment]
@francesco-romano You think we fixed this?

**Comment by francesco-romano** [comment]
Honestly, I don't remember.
Let's close this for now, and reopen it in case it hasn't been fixed yet.
