### ISSUE TITLE
Move repository to robotology

### ISSUE THREAD

**Issue by drdanz** [robotology/icub-gazebo#20]
As discussed with @traversaro, this repository should be moved to [robotology](https://github.com/robotology)

cc-issue: robotology/robotology.github.io#2

**Comment by traversaro** [comment]
:+1:

**Comment by drdanz** [comment]
@traversaro does :+1: mean that you are ready for moving this?

**Comment by traversaro** [comment]
yes

**Comment by drdanz** [comment]
Done!
