### ISSUE TITLE
[model-generation] Fix torso_roll axis in model generation

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-gazebo#23]
https://github.com/robotology-playground/icub-gazebo/commit/c9339bbef7e53ee57ef62132087d3367b6407682

**Comment by DanielePucci** [comment]
:+1:

**Comment by traversaro** [comment]
This is now enforced by the tests in `icub-model-generator`, see https://github.com/robotology-playground/icub-model-generator/blob/2e96973a3c68ce54ac553190b060a0e56220e1f6/tests/icub-model-test.cpp#L230 .
