### ISSUE TITLE
Remove ControlBoardWrapper warnings

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-gazebo#24]
See https://github.com/robotology/gazebo-yarp-plugins/issues/210#issuecomment-156236465 . 

@barbalberto @liesrock @EnricoMingo @arocchi 
Can you confirm me that the walkman superbuild is pointing to the `master` branch of YARP ? Thanks.

**Comment by barbalberto** [comment]
Not exactly the master but updated at the beginning of month, commit 2fae6159e0d4f4a574c68188402d0857e07611d0. Anywayt it'll need to update again when we fix the newly found bug on networkClock #624

**Comment by liesrock** [comment]
I confirm what @barbalberto wrote.

**Comment by traversaro** [comment]
Thank you guys. :+1:

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/icub-gazebo/issues/51 and https://github.com/robotology/icub-gazebo/issues/56 .
