### ISSUE TITLE
Found bug in yarpmotorgui configuration file

### ISSUE THREAD

**Issue by UChervet** [robotology/icub-gazebo#28]
Hello,

The yarpmotorgui configuration file is missing some parameters for the last three head joints.
Therefore by clicking home on the GUI we get an error.

[head_zero]
//                  0          1        2         3          4          5
PositionZero      0.0        0.0      0.0      
VelocityZero     10.0       10.0     10.0  

We modified the file adding the missing position and velocity values and this fixed the problem.

Should we (me and @serena-ivaldi)  correct the file ?

**Comment by traversaro** [comment]
Yes, it is the same modification that @misaki43 did in https://github.com/robotology/codyco-modules/pull/178 (the reason is that until few months ago the gazebo simulator did not had support for the eyes). Feel free to open a PR with the correct version, thanks!
