### ISSUE TITLE
iCub with hands and Cameras

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-gazebo#40]
@traversaro @randaz81 
Ciao Guys, 

I see that we dont have any gazebo model with hands and cameras together. I am not sure if there is any particular reason for it. If not can I push it to master? Please let me know 

Thank you

**Comment by traversaro** [comment]
I think it make sense to just add cameras to `icub_with_hands` and then to remote `icub_with_cameras`.

**Comment by traversaro** [comment]
@Yeshasvitvs In general for proposing any modification feel free to open a PR so we can discuss directly there.

**Comment by Yeshasvitvs** [comment]
Yes that is how I am using it. Added the camera plugins and conf files and modified the sdf of hands model 

Cheers

**Comment by claudiofantacci** [comment]
I am also interested in a Gazebo iCub model with hands (hence torso + arms) and cameras.

@Yeshasvitvs do you have a model which is also fixed, say, at the ROOT so that it does not fall?

**Comment by Yeshasvitvs** [comment]
@claudiofantacci  I have a floating base model with hands and cameras

**Comment by claudiofantacci** [comment]
Yeah that fine, will do the job 😄 !
Thanks!

**Comment by Yeshasvitvs** [comment]
see https://github.com/robotology/icub-gazebo/pull/47
