### ISSUE TITLE
[icub_with_hands] hands tremor + finger twitching

### ISSUE THREAD

**Issue by emilio-cartoni** [robotology/icub-gazebo#46]
After the recent fixes for the issue in robotology/QA#155 I noticed that the hands of the icub_with_hands model now have a constant small tremor and sometimes a finger twitches for a split second.
This happens constantly without sending any command to the iCub.

**Comment by traversaro** [comment]
I think we will check this tomorrow in IFI-Day with @randaz81 and @Yeshasvitvs .

**Comment by Yeshasvitvs** [comment]
@randaz81 @traversaro this is solved! see https://github.com/robotology/icub-gazebo/pull/50
