### ISSUE TITLE
Provide a world for make-it-roll tutorial

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-gazebo#57]
Provide a `.world` file to simplify reproducing the [`make-it-roll`](https://github.com/vvv-school/make-it-roll) tutorial on Gazebo.

**Comment by gabrielenava** [comment]
The world file has been created in [another repository](https://github.com/robotology-playground/icub-gazebo-wholebody/tree/master/worlds/iCub_and_Table), thus we can close the issue.
