### ISSUE TITLE
What happend to icub_chair branch

### ISSUE THREAD

**Issue by rlober** [robotology/icub-gazebo#60]
Hey all,

What happened to the `icub_chair` branch we were using for demo stuff? Seems to have been `-d`ed...

@traversaro @gabrielenava @DanielePucci @francesco-romano

**Comment by gabrielenava** [comment]
Hi! the models related to this demo have been moved to the new repository [icub-gazebo-wholebody](https://github.com/robotology-playground/icub-gazebo-wholebody)
for further info you can refer to this issue  https://github.com/robotology-playground/WBI-Toolbox-controllers/issues/39

**Comment by rlober** [comment]
Great, thanks @gabrielenava
