### ISSUE TITLE
Remove the iCubHeidelberg01 model

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-gazebo#70]
The iCubHeidelberg01 model present in this repo is not maintained and  it has not been migrated to the new model generation infrastructure at https://github.com/robotology/icub-model-generator . Unless @hu-yue is aware of anyone working on iCubHeidelberg01, I think we can drop it from the repo.

**Comment by traversaro** [comment]
cc @diegoferigo

**Comment by hu-yue** [comment]
The only person I can think of is @mhubii, if he is not using it, maybe he knows if someone is using it in Heidelberg. 
cc @KevinAStein?

**Comment by mhubii** [comment]
I am using it thats true, and it would be cool to have it around until I have finished :)

**Comment by mhubii** [comment]
and actually I am not so dependent on whether or not the model can be found here. So if it makes you feel like you could clean up your code by that, do it.

**Comment by traversaro** [comment]
This repo has been deprecated some time ago (see https://github.com/robotology/robotology-superbuild/issues/542), so it is not really important to delete this specific model.
