### ISSUE TITLE
Use grabberDual instead of grabber in icub camera configuration files

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-gazebo#78]
In files 

https://github.com/robotology/icub-gazebo/blob/master/icub/conf/left_camera.ini

and

https://github.com/robotology/icub-gazebo/blob/master/icub/conf/right_camera.ini

`grabber` is used as the YARP device exposing images to the YARP network.

However, `grabber` is now deprecated in YARP and we should switch to `grabberDual` which is the new default one to avoid issues, e.g. see https://github.com/robotology/gazebo-yarp-plugins/issues/498

If ok, I can open a PR for that.

**Comment by traversaro** [comment]
Thanks for the issue, feel free to open a PR, thanks!

**Comment by traversaro** [comment]
Just to understand, `grabberDual` is a drop-in replacement for `grabber` or there are some differences the users should be aware of?

**Comment by traversaro** [comment]
Related issue: https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/100 .

**Comment by traversaro** [comment]
Docs: 
* `grabber` docs: http://www.yarp.it/classServerFrameGrabber.html 
* `grabberDual` docs: http://www.yarp.it/classServerGrabber.html

**Comment by xEnVrE** [comment]
> Just to understand, grabberDual is a drop-in replacement for grabber or there are some differences the users should be aware of?

Hi @traversaro, I am not that into the topic. It seems that it support two cameras at the same time.

**Comment by traversaro** [comment]
I guess @Nicogene can help us answer this question.

**Comment by Nicogene** [comment]
> Just to understand, grabberDual is a drop-in replacement for grabber or there are some differences the users should be aware of?

`grabberDual` supersed all the `grabber` functionalities, except for the support also of the audio stream, but recently in YARP the audio management is changed a lot, then I suspect that it doesn't work anymore.
I agree to port the ini to use `grabberDual`, it is the now the default for all the camera devices

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/icub-gazebo/pull/79 .
