### ISSUE TITLE
The simulator opens ports with icubGazeboSim, should we call them icubSim?

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-gazebo#8]

**Comment by traversaro** [comment]
Possible time to reevaluate this, perhaps at next IFI.

**Comment by claudiofantacci** [comment]
Yeah I agree, we should discuss this during the next IFI 😄

**Comment by randaz81** [comment]
IFI day passed and we haven't discussed this yet..😄
I think this is an important issue, expecially to simplify the use of the cartesiancontroller configuration files with gazebo (i.e. the files contained in the icub-main\app\simCartesianControl folder)

**Comment by traversaro** [comment]
We discussed of this with @randaz81 and @pattacini and at the moment we all agree that this would definitely simplify sharing configuration files between `icubSim` and iCub simulated on Gazebo (see https://github.com/robotology/gazebo-yarp-plugins/issues/132). 

This would be true even for calling it simply `icub`, but changing too much would be probably risky. : )
 I will start know to disseminate the news of this change, to properly make sure that everyone knows about it before we change it on the `master` branch.

**Comment by traversaro** [comment]
cc @robotology/codyco-developers Please take a look at this issue. The changes should be minimal, as we just need to change `icubGazeboSim` to `icubSim` in all relevant script/configuration files, but please be aware of it.

**Comment by jeljaik** [comment]
👍🏽

**Comment by traversaro** [comment]
For reference: this can already be done by opening the `icub-gazebo/icub/conf/gazebo_icub_robotname.ini` ( `iCubHeidelberg01_model/conf/gazebo_iCubHeidelberg01_robotname.ini` for iCubHeidelberg01 ) and modifying its content from `gazeboYarpPluginsRobotName icubGazeboSim` to `gazeboYarpPluginsRobotName icubSim` . 

The same can be done for using any kind of prefix you may want, for example `icub`.

**Comment by claudiofantacci** [comment]
👍

**Comment by traversaro** [comment]
PR already created: 
* [ ] https://github.com/robotology/icub-gazebo/issues/53
* [ ] https://github.com/robotology/yarp-wholebodyinterface/pull/60

Repo still to update : 
* [ ] https://github.com/ocra-recipes/ocra-recipes/search?utf8=%E2%9C%93&q=icubGazeboSim
* [ ] https://github.com/ocra-recipes/ocra-wbi-plugins/search?utf8=%E2%9C%93&q=icubGazeboSim
* [ ] https://github.com/robotology/mex-wholebodymodel/search?utf8=%E2%9C%93&q=icubGazeboSim @gabrielenava 
* [ ] https://github.com/robotology-playground/WBI-Toolbox-controllers/search?utf8=%E2%9C%93&q=icubGazeboSim @gabrielenava 
* [ ] https://github.com/robotology/codyco-modules/search?p=5&q=icubGazeboSim&utf8=%E2%9C%93
* [ ] https://github.com/robotology-playground/torque-control-params-estimation/search?utf8=%E2%9C%93&q=icubGazeboSim

**Comment by traversaro** [comment]
Fixed almost a week ago, but we noticed it only now, see https://github.com/robotology/icub-gazebo/pull/53#issuecomment-265433940 . This has definitely been fixed now.
